# Generated by Django 4.1.1 on 2022-11-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.TimeField(default='11:10'),
            preserve_default=False,
        ),
    ]
